server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://0.0.0.0:2222/postgres
    username: postgres
    password: postgres

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db.migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql

logging:
  level:
    org.flywaydb: DEBUG