server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:2222/postgresprod
    username: postgres
    password: postgres

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db.migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql

  jackson:
    default-property-inclusion: non-null

logging:
  level:
    org.flywaydb: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: ed64e614-8709-48b2-bda2-fee2a9204030
  expiration: 999999